//chartsActions
export const REQUEST_CHART_POINTS = 'REQUEST_CHART_POINTS';
export const RECIVE_CHART_POINTS = 'RECIVE_CHART_POINTS';
export const CLEAR_CHART_POINTS = 'CLEAR_CHART_POINTS';

export const REQUEST_COMPANY_DATA = 'REQUEST_COMPANY_DATA';
export const RECIVE_COMPANY_DATA = 'RECIVE_COMPANY_DATA';
export const CLEAR_COMPANY_DATA = 'CLEAR_COMPANY_DATA';

export const SET_COMPANY_SYMBOL = 'SET_COMPANY_SYMBOL';
export const CLEAR_COMPANY_SYMBOL = 'CLEAR_COMPANY_SYMBOL';

export const SET_PERIOD = 'SET_PERIOD';

//uiNotificationsActions
export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';
export const ADD_ALLERT_MESSAGE = 'ADD_ALLERT_MESSAGE'
export const CLEAR_ALL_MESSAGES = 'CLEAR_ALL_MESSAGES';
export const CLEAR_ERROR_MESSAGES = 'CLEAR_ERROR_MESSAGES';